Repository MrKrishnaAgarwal/Hacktoberfest2022, pull requests merged in 2022-09, with the labels that each got.

#30 Sum of two number in Python.py
  Python/Sum of 2 no.s
Labels: enhancement, beginner-friendly

#36 Add python Tkinter Program
  Python/Tkinter.py
Labels: enhancement, beginner-friendly

#55 Issue #39 Height of Binary Tree Algorithm
  Java/height_of_binary_tree.java
Labels: enhancement, good first issue

#65 Update Practice_PR.md
  Practice_PR.md
Labels: hacktoberfest

#61 Decimal to Binary Convert
  C++/DecimaltoBinary.cpp
Labels: enhancement, beginner-friendly

#62 feat: added js code - renanlmiranda
  JavasScript/types.js
Labels: enhancement, beginner-friendly

#64 Basic drawing in Python with Turtle
  Python/Drawing with Turtle
Labels: enhancement, beginner-friendly
